### ISSUE TITLE
Crash on World Creation and Resource Reload Fail

### ISSUE THREAD

**Issue by CraftyZombie** [RuffleSteels/Jebbed-Out#1]
Mod Version: 1.0
Fabric Version: 0.15.11
Minecraft Version: 1.20.1

Other Mods: 
Just Fabric API

Steps to Reproduce:
1. Start up game. Notice 'Resource Reload Failed' notification in the top right of the screen.
2. Attempt to create a world.
3. Crash.

Logs:
(latest.log and crash report)
https://gist.github.com/CraftyZombie/1f43f3e2ed93d19a087ecfa66c975cea

**Comment by RuffleSteels** [comment]
Hi,
This appears not to be the case for a clean instance my end, could you please tell me more about your instance e.g resource packs installed, config settings

**Comment by CraftyZombie** [comment]
I'm using a clean Prism Launcher instance. No resource packs or config settings modified.
However, I am on OSX with an M1 chip. Do you think that's the issue?

**Comment by RuffleSteels** [comment]
sorry but the mac architecture breaks a lot of mods, and it seems to include this once as well. There is no way I myself can account for these errors, sorry.
